name = "Leantix"
version = "0.1.0"
defaultTargets = ["leantix"]


[[lean_lib]]
name = "Leantix"

[[lean_exe]]
name = "leantix"
root = "Main"

[[lean_lib]]
name = "Golitex"

[[lean_lib]]
name = "Tests"

[[lean_exe]]
name = "golitex-lint"
root = "Scripts.GolitexLintMain"

[[lean_exe]]
name = "test"
root = "Tests.Main"
